# Generated by Django 6.0.6 on 2026-08-11 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Party Name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('phone_1', models.CharField(blank=True, max_length=20, verbose_name='Phone Number 1')),
                ('phone_2', models.CharField(blank=True, max_length=20, verbose_name='Phone Number 2')),
                ('pincode', models.CharField(blank=True, max_length=10, verbose_name='Pincode')),
                ('locality', models.CharField(blank=True, max_length=100, verbose_name='Locality')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='District')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='State')),
                ('manual_address', models.TextField(blank=True, verbose_name='Manual Address')),
                ('company_name', models.CharField(blank=True, max_length=150, verbose_name='Party Company Name')),
                ('owner_name', models.CharField(blank=True, max_length=150, verbose_name='Party Owner Name')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='parties/photos/', verbose_name='Profile Picture')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Balance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('party_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parties', to='parties.partytype', verbose_name='Party Type')),
            ],
            options={
                'verbose_name_plural': 'Parties',
                'ordering': ['-created_at'],
            },
        ),
    ]
