# Generated by Django 6.0.6 on 2026-08-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='name',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Party Name'),
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['-created_at'], name='parties_par_created_59195b_idx'),
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['name'], name='parties_par_name_645a31_idx'),
        ),
    ]
