# Generated by Django 6.0.6 on 2026-08-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_company_owner_name_company_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='font_size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium (Default)'), ('large', 'Large'), ('xlarge', 'Extra Large')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='object_size',
            field=models.CharField(choices=[('small', 'Small (Compact)'), ('medium', 'Medium (Default)'), ('large', 'Large'), ('xlarge', 'Extra Large')], default='medium', max_length=10),
        ),
    ]
