# Generated by Django 6.0.6 on 2026-07-17 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_company_systemsettings_delete_testdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('hex_code', models.CharField(max_length=7)),
                ('category', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='primary_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_settings', to='core.color'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='secondary_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_settings', to='core.color'),
        ),
    ]
