# Generated by Django 6.0.6 on 2026-08-12 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_systemsettings_font_size_systemsettings_object_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='font_size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium (Default)'), ('large', 'Large'), ('xlarge', 'Extra Large')], default='small', max_length=10),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='object_size',
            field=models.CharField(choices=[('small', 'Small (Compact)'), ('medium', 'Medium (Default)'), ('large', 'Large'), ('xlarge', 'Extra Large')], default='small', max_length=10),
        ),
        migrations.CreateModel(
            name='ActionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=255)),
                ('action', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True, null=True)),
                ('action_type', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('SYSTEM', 'System'), ('CLEAR', 'Clear')], default='SYSTEM', max_length=50)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Action History',
                'verbose_name_plural': 'Action Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
