# Generated by Django 6.0.6 on 2026-08-12 08:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_systemsettings_font_size_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionhistory',
            name='action_type',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('SYSTEM', 'System'), ('CLEAR', 'Clear')], db_index=True, default='SYSTEM', max_length=50),
        ),
        migrations.AlterField(
            model_name='actionhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='actionhistory',
            index=models.Index(fields=['-created_at'], name='core_action_created_96f151_idx'),
        ),
        migrations.AddIndex(
            model_name='actionhistory',
            index=models.Index(fields=['action_type'], name='core_action_action__95dc1c_idx'),
        ),
    ]
