# Generated by Django 6.0.6 on 2026-07-17 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.currency'),
        ),
    ]
