# Generated by Django 6.0.6 on 2026-08-12 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_actionhistory_action_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrashItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('PARTY', 'Party'), ('TRANSACTION', 'Transaction'), ('STAFF', 'Staff Member')], db_index=True, max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('deleted_by_name', models.CharField(blank=True, max_length=255)),
                ('serialized_data', models.JSONField()),
                ('deleted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_trash_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trash Item',
                'verbose_name_plural': 'Trash Items',
                'ordering': ['-deleted_at'],
                'indexes': [models.Index(fields=['-deleted_at'], name='core_trashi_deleted_9e599a_idx'), models.Index(fields=['item_type'], name='core_trashi_item_ty_67270d_idx')],
            },
        ),
    ]
