# Generated by Django 6.0.6 on 2026-07-17 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_systemsettings_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='symbol',
        ),
    ]
