# Generated by Django 6.0.6 on 2026-08-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='raw_password',
            field=models.CharField(blank=True, help_text='Stored plain password for owner reference', max_length=128, null=True),
        ),
    ]
