# Generated by Django 6.0.6 on 2026-08-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_raw_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('STAFF', 'Staff')], db_index=True, default='STAFF', max_length=10),
        ),
    ]
