from django.urls import path
from .views import (
    company_profile,
    dashboard,
    edit_company,
    export_company_pdf,
    export_company_card_pdf,
    settings,
    color_search_api,
    color_create_api,
    action_history_list,
    action_history_delete_item,
    action_history_clear_all,
    trash_bin_list,
    trash_bin_restore,
    trash_bin_delete_permanent,
    trash_bin_clear_all,
)

urlpatterns = [
    path('', dashboard, name='dashboard'),
    path('company-profile/', company_profile, name='company_profile'),
    path('company-export-pdf/', export_company_pdf, name='company_export_pdf'),
    path('company-card-pdf/', export_company_card_pdf, name='company_card_pdf'),
    path('company-edit/', edit_company, name='edit_company'),
    path('settings/', settings, name='settings'),
    path('colors/search/', color_search_api, name='color_search_api'),
    path('colors/create/', color_create_api, name='color_create_api'),
    path('history/', action_history_list, name='action_history_list'),
    path('history/<int:pk>/delete/', action_history_delete_item, name='action_history_delete_item'),
    path('history/clear-all/', action_history_clear_all, name='action_history_clear_all'),
    path('trash/', trash_bin_list, name='trash_bin_list'),
    path('trash/<int:pk>/restore/', trash_bin_restore, name='trash_bin_restore'),
    path('trash/<int:pk>/permanent-delete/', trash_bin_delete_permanent, name='trash_bin_delete_permanent'),
    path('trash/clear-all/', trash_bin_clear_all, name='trash_bin_clear_all'),
]