# Generated by Django 6.0.6 on 2026-08-12 08:09

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0002_alter_party_created_at_alter_party_name_and_more'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_time',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Date & Time'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('receipt', 'Receipt (Money In)'), ('payment', 'Payment (Money Out)')], db_index=True, default='receipt', max_length=20, verbose_name='Transaction Type'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['-date_time', '-created_at'], name='transaction_date_ti_1f7aad_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type'], name='transaction_transac_09d7ec_idx'),
        ),
    ]
